### PR TITLE
Feat - Hide Wizeline branded

### PR DESCRIPTION
**Pull request by MoisesFlores22**
## What does this PR do?

Changes the powered by wizeline and makes it disappear when a text pass trough it

## Pictures 

|Before|After|
|---|---|
|screen shot 2017-08-22 at 1 34 51 pm|screen shot 2017-08-22 at 4 36 48 pm|

### CODE REVIEW

**Comment by isa-bel** [comment]
@MoisesFlores22 The font for `Powered ..` in the "after" screenshot looks different, is that ok?

**Comment by MoisesFlores22** [comment]
yes UX give it to me

**Comment by isa-bel** [comment]
🤔 Can you ask them again? I think it is using Times New Roman, that is not part of the Wizeline branding. Also, if the other image is no longer used, can you remove it?

**Comment by isa-bel** [comment]
Actually, I think that is the problem, maybe. The image uses `Nunito` but because its not available, it uses the default font.

**Pull request merged**
