### PR TITLE
change on the top image

### PR DESCRIPTION
**Pull request by MoisesFlores22**
This PR Change the top image

Before:

screen shot 2017-01-31 at 1 43 00 pm

after:

screen shot 2017-01-31 at 1 45 52 pm

### CODE REVIEW

**Comment by erikvilla** [comment]
Why did you change the file instead of the svg content?

**Comment by MoisesFlores22** [comment]
i thought it was easier to change the file 😅 i'm not used to change the content of a svg

**Comment by erikvilla** [comment]
The next time you could just change the svg content, LGTM by now

**Comment by MoisesFlores22** [comment]
could you approve 🙏  jejeje, next time i will do that

**Pull request merged**
